services:
  - type: web
    name: bwm-xmd-quantum
    env: node
    plan: free
    region: oregon
    branch: main
    repo: https://github.com/Bavo-G/BWM-XMD-QUANTUM
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SESSION_ID
        value: your_real_session_id_here
      - key: PREFIX
        value: "."
      - key: PRESENCE
        value: "true"
